"""Emit paper/numbers.tex with \\newcommand macros, all traceable to result CSVs.

Every numeric macro used in the paper body is generated here from results/*.csv,
so there are no hand-typed numbers in the prose. Re-run after experiments finish.
"""

from __future__ import annotations

import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "paper", "numbers.tex")


def cmd(name, val):
    return f"\\newcommand{{\\{name}}}{{{val}}}"


def main():
    L = ["% Auto-generated by paper/inject_numbers.py — do not edit by hand."]

    e1p = os.path.join(RESULTS, "e1_results.csv")
    if os.path.exists(e1p):
        df = pd.read_csv(e1p).set_index("method")

        def g(method, col):
            return float(df.loc[method, col])

        # weighted cost for the headline methods
        mapping = {
            "AlwaysLocal": "Local",
            "AlwaysEdge": "Edge",
            "Random": "Random",
            "Greedy": "Greedy",
            "DQN[256x256]": "DQNbig",
            "DQN[64x64]": "DQNmid",
            "DQN[16x16]": "DQNsmall",
            "PPO[64x64]": "PPO",
        }
        for m, tag in mapping.items():
            if m in df.index:
                L.append(cmd(f"cost{tag}", f"{g(m,'cost_mean'):.3f}"))
                L.append(
                    cmd(
                        f"miss{tag}",
                        f"{g(m,'miss_mean') if 'miss_mean' in df else g(m,'miss_rate_mean'):.1f}",
                    )
                )
        # footprint of the mid DQN and big DQN
        for m, tag in [
            ("DQN[64x64]", "DQNmid"),
            ("DQN[256x256]", "DQNbig"),
            ("DQN[16x16]", "DQNsmall"),
        ]:
            if m in df.index and pd.notna(df.loc[m, "params"]):
                L.append(cmd(f"params{tag}", f"{int(df.loc[m,'params'])}"))
                L.append(cmd(f"size{tag}", f"{float(df.loc[m,'size_kb']):.1f}"))
                L.append(cmd(f"infer{tag}", f"{float(df.loc[m,'infer_us']):.1f}"))
        # DQN64 vs Greedy ratio
        if "DQN[64x64]" in df.index and "Greedy" in df.index:
            ratio = g("DQN[64x64]", "cost_mean") / g("Greedy", "cost_mean")
            L.append(cmd("dqnGreedyRatio", f"{ratio:.2f}"))

    e3 = os.path.join(RESULTS, "e3_quant_detail.csv")
    if os.path.exists(e3):
        q = pd.read_csv(e3).iloc[0]
        L.append(cmd("quantSizeFp", f"{q['size_kb_fp32']:.1f}"))
        L.append(cmd("quantSizeInt", f"{q['size_kb_int8']:.1f}"))
        L.append(cmd("quantInferFp", f"{q['infer_us_fp32']:.1f}"))
        L.append(cmd("quantInferInt", f"{q['infer_us_int8']:.1f}"))
        L.append(cmd("quantCost", f"{q['cost_mean']:.3f}"))
        L.append(
            cmd("quantSizeRed", f"{100*(1-q['size_kb_int8']/q['size_kb_fp32']):.0f}")
        )

    e5 = os.path.join(RESULTS, "e5_llm_summary.csv")
    e5e = os.path.join(RESULTS, "e5_llm_episodes.csv")
    if os.path.exists(e5) and os.path.exists(e5e):
        s = pd.read_csv(e5)
        e = pd.read_csv(e5e)
        word = {"P1": "Pone", "P2": "Ptwo"}  # LaTeX macro names cannot contain digits
        for _, r in s.iterrows():
            tag = word.get(r["variant"], r["variant"])
            L.append(cmd(f"llm{tag}lat", f"{r['decision_latency_s_mean']:.2f}"))
            L.append(cmd(f"llm{tag}parse", f"{r['parse_failure_pct']:.1f}"))
            L.append(cmd(f"llm{tag}agree", f"{r['agreement_greedy_pct']:.1f}"))
            ep = e[e["variant"] == r["variant"]]
            if len(ep):
                L.append(cmd(f"llm{tag}cost", f"{ep['cost'].mean():.3f}"))
        gref = e[e["variant"] == "Greedy-ref"]
        if len(gref):
            L.append(cmd("llmGreedyCost", f"{gref['cost'].mean():.3f}"))
        L.append(cmd("llmModel", str(s.iloc[0]["model"]).replace("_", "\\_")))
        L.append(cmd("llmEpisodes", str(int(s.iloc[0]["n_episodes"]))))

    e4 = os.path.join(RESULTS, "e4_robustness.csv")
    if os.path.exists(e4):
        d = pd.read_csv(e4)

        def gv(shift, scale, method):
            m = d[
                (d["shift"] == shift) & (d["scale"] == scale) & (d["method"] == method)
            ]
            return float(m["cost"].iloc[0])

        L.append(cmd("robBgLo", f"{gv('bgload',0.5,'DQN[64,64]'):.3f}"))
        L.append(cmd("robBgHi", f"{gv('bgload',2.0,'DQN[64,64]'):.3f}"))
        L.append(cmd("robRateLoD", f"{gv('rate',0.5,'DQN[64,64]'):.3f}"))
        L.append(cmd("robRateLoG", f"{gv('rate',0.5,'Greedy'):.3f}"))
        L.append(cmd("robRateHiD", f"{gv('rate',2.0,'DQN[64,64]'):.3f}"))
        L.append(cmd("robRateHiG", f"{gv('rate',2.0,'Greedy'):.3f}"))

    e6 = os.path.join(RESULTS, "e6_real_trace.csv")
    if os.path.exists(e6):
        d6 = pd.read_csv(e6)
        has_ds = "dataset" in d6.columns

        def _row(method, ds=None):
            sub = d6[d6["method"] == method]
            if has_ds and ds is not None:
                sub = sub[sub["dataset"] == ds]
            return sub.iloc[0]

        nasa = "NASA-HTTP Jul'95"
        L.append(cmd("realDQN", f"{_row('DQN[64,64]', nasa)['cost_mean']:.3f}"))
        L.append(cmd("realGreedy", f"{_row('Greedy', nasa)['cost_mean']:.3f}"))
        L.append(cmd("realLocal", f"{_row('AlwaysLocal', nasa)['cost_mean']:.3f}"))
        L.append(cmd("realCV", f"{_row('DQN[64,64]', nasa)['dt_cv']:.2f}"))
        if has_ds and (d6["dataset"] == "ClarkNet Aug'95").any():
            ck = "ClarkNet Aug'95"
            L.append(cmd("realDQNck", f"{_row('DQN[64,64]', ck)['cost_mean']:.3f}"))
            L.append(cmd("realGreedyck", f"{_row('Greedy', ck)['cost_mean']:.3f}"))
            L.append(cmd("realCVck", f"{_row('DQN[64,64]', ck)['dt_cv']:.2f}"))

    e7 = os.path.join(RESULTS, "e7_scarce_battery.csv")
    if os.path.exists(e7):
        d7 = pd.read_csv(e7).set_index("method")
        sd = d7.loc["DQN[64,64]", "cost_mean"]
        sg = d7.loc["Greedy", "cost_mean"]
        L.append(cmd("scarceDQN", f"{sd:.3f}"))
        L.append(cmd("scarceGreedy", f"{sg:.3f}"))
        L.append(cmd("scarceLocal", f"{d7.loc['AlwaysLocal','cost_mean']:.3f}"))
        L.append(cmd("scarceGain", f"{100*(sg-sd)/sg:.1f}"))

    e8 = os.path.join(RESULTS, "e8_actions.csv")
    if os.path.exists(e8):
        d8 = pd.read_csv(e8).set_index("method")
        for key, m in [("Dq", "DQN[64,64]"), ("Gr", "Greedy")]:
            L.append(cmd(f"act{key}Local", f"{d8.loc[m,'local_pct']:.0f}"))
            L.append(cmd(f"act{key}Edge", f"{d8.loc[m,'edge_pct']:.0f}"))
            L.append(cmd(f"act{key}Cloud", f"{d8.loc[m,'cloud_pct']:.0f}"))

    e10 = os.path.join(RESULTS, "e10_cot_summary.csv")
    e10e = os.path.join(RESULTS, "e10_cot_episodes.csv")
    if os.path.exists(e10) and os.path.exists(e10e):
        s10 = pd.read_csv(e10).iloc[0]
        ep10 = pd.read_csv(e10e)
        L.append(cmd("llmCotCost", f"{ep10['cost'].mean():.3f}"))
        L.append(cmd("llmCotAgree", f"{s10['agreement_greedy_pct']:.0f}"))
        L.append(cmd("llmCotLat", f"{s10['decision_latency_s_mean']:.2f}"))
        L.append(cmd("llmCotEp", f"{int(s10['n_episodes'])}"))

    e11 = os.path.join(RESULTS, "e11_contention.csv")
    if os.path.exists(e11):
        d11 = pd.read_csv(e11).set_index("method")
        L.append(cmd("contDQN", f"{d11.loc['DQN[64,64]','cost_mean']:.3f}"))
        L.append(cmd("contGreedy", f"{d11.loc['Greedy','cost_mean']:.3f}"))

    e9 = os.path.join(RESULTS, "e9_metered_cloud.csv")
    if os.path.exists(e9):
        d9 = pd.read_csv(e9).set_index("method")
        md = d9.loc["DQN[64,64]", "cost_mean"]
        mg = d9.loc["Greedy", "cost_mean"]
        L.append(cmd("meterDQN", f"{md:.3f}"))
        L.append(cmd("meterGreedy", f"{mg:.3f}"))
        L.append(cmd("meterLocal", f"{d9.loc['AlwaysLocal','cost_mean']:.3f}"))
        L.append(cmd("meterGain", f"{100*(mg-md)/mg:.1f}"))

    pj = os.path.join(RESULTS, "e1_paired_test.json")
    if os.path.exists(pj):
        import json

        j = json.load(open(pj))
        L.append(cmd("pairedDiff", f"{j['diff']:.3f}"))
        # report p as "< 0.001" when tiny
        p = j["p_t"]
        L.append(cmd("pairedP", "<0.001" if p < 1e-3 else f"{p:.3f}"))

    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)-1} macros)")


if __name__ == "__main__":
    main()
